[versions]
assertj = "3.27.3"
buildTimeTracker = "5.0.1"
guava = "33.4.8-jre"
inflector = "1.3"
jupiter = "5.13.4"
lang3 = "3.18.0"
systemLambda = "1.2.1"

[libraries]
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
bytebuddy = { module = "net.bytebuddy:byte-buddy" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "lang3" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiter" }
inflector = { group = "org.atteo", name = "evo-inflector", version.ref = "inflector" }
system-lambda = { group = "com.github.stefanbirkner", name = "system-lambda", version.ref = "systemLambda" }

[bundles]
junit-jupiter = ["junit-jupiter-api", "junit-jupiter-engine", "junit-jupiter-params"]

[plugins]
build-time-tracker = { id = "com.asarkar.gradle.build-time-tracker", version.ref = "buildTimeTracker" }
